name: Polaris and Blackduck CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # -- Build your project here -- eg. mvn clean package
      - name: Polaris
        id: polaris
        continue-on-error: true
        uses: blackducksoftware/github-action@2.0.0
        with:
          args: '--polaris.url="${{ secrets.POLARIS_URL}}" --polaris.access.token="${{ secrets.POLARIS_TOKEN}}" --detect.detector.search.exclusion.defaults=true --detect.detector.search.exclusion.paths="/home/runner/work/GitActionsX/GitActionsX" --detect.tools="POLARIS"'
      - name: Synopsys Detect
        id: blackduck
        continue-on-error: true
        uses: blackducksoftware/github-action@2.0.0
        with:
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true --detect.report.timeout=600 --logging.level.detect=TRACE --logging.level.com.synopsys.integration=DEBUG'
